name: Download History Data

on:
  workflow_dispatch:
    inputs:
      symbols:
        description: 'Symbols'
        required: false
      interval:
        description: 'Intervals'
        required: false
        default: '1mo'

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Download
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: python python/download-kline.py -s ${{ github.event.inputs.symbols }} -i ${{ github.event.inputs.interval }} -skip-daily 1 -t spot
